### ISSUE TITLE
configFailurePolicy not working when using YAML instead of XML

### ISSUE THREAD

**Issue by ghost** [testng-team/testng#1351]
### TestNG Version
6.10

### Expected behavior
I am in the process of converting my TestNG XML files to YAML, but when I add the configFailurePolicy to my YAML file and I try to run it from maven I am getting the following:

```java
[ERROR] org.testng.TestNGException: org.yaml.snakeyaml.error.YAMLException: Unable to find enum value 'continue' for enum class: org.testng.xml.XmlSuite$FailurePolicy
[ERROR] at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:325)
[ERROR] at org.testng.TestNG.run(TestNG.java:1081)
```

Maven Command:
```shell
mvn -DtestngXmlFile=testng.yaml clean test
```

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
This is the YAML file I am using:

```yaml
name: admin-suite
configFailurePolicy: continue
parallel: methods
timeOut: 180000000
threadCount: 1

tests:
  - name: admin-webservices
    preserveOrder: true
    parameters: {
      testSuite: admin
    }

    xmlPackages:
      - name: com.company.tests.*
```

This is the XML file that I am using that works:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="admin-suite" configfailurepolicy="continue" parallel="methods" time-out="180000000" thread-count="1">
    <test name="admin-webservices" preserve-order="true">
        <parameter name="testSuite" value="admin"/>
        <packages>
            <package name="com.company.tests.*"/>
        </packages>
    </test>
</suite>
```
