### ISSUE TITLE
Child suite does not obey threadCount parameter

### ISSUE THREAD

**Issue by dsankouski** [testng-team/testng#2686]
### TestNG Version
7.4

Steps to reproduce:
- Create 2 suites:
```yaml
name: Parent suite

suiteFiles:
  - ./inherit-thread-count-child.yaml
```

```yaml
name: Child suite

tests:
  - name: Tests
    classes:
      - test.thread.Sample2
      - test.thread.Sample1
```
- Run parent suite with `threadCount` parameter equal 2

### Expected behavior
Run should be executed in 2 threads

### Actual behavior
Run executed in 1 thread

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Tests: #2687
